export const url = '172.17.0.1'
export const port = '8080'
export const entryPointUsers = 'users'
export const entryPointRecharges = 'recharges'
export const entryPointPayments = 'payments'
export const entryPointInternalTransactions = 'internal_transactions'
export const entryPointBalances = 'balance'
export const entryPointMovements = 'movements'